-- 코드를 입력하세요

# SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, (SUM(s.SALES) * b.PRICE) AS SALES
# FROM BOOK_SALES s JOIN BOOK b USING(BOOK_ID) JOIN AUTHOR a USING(AUTHOR_ID)
# WHERE b.BOOK_ID IN 
#     (SELECT s.BOOK_ID
#     FROM BOOK_SALES s
#     WHERE DATE_FORMAT(s.SALES_DATE, '%Y-%m') = '2022-01'
#     GROUP BY s.BOOK_ID)  
# GROUP BY a.AUTHOR_ID, b.CATEGORY
# ORDER BY a.AUTHOR_ID ASC, b.CATEGORY DESC;

SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(s.SALES * b.PRICE) AS SALES
FROM BOOK_SALES s
JOIN BOOK b ON s.BOOK_ID = b.BOOK_ID
JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE DATE_FORMAT(s.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY
ORDER BY a.AUTHOR_ID ASC, b.CATEGORY DESC;
