-- 코드를 입력하세요

SELECT info.REST_ID, info.REST_NAME, info.FOOD_TYPE, info.FAVORITES, info.ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO info JOIN REST_REVIEW review ON info.REST_ID = review.REST_ID
WHERE SUBSTR(info.ADDRESS, 1, 2) = '서울'
GROUP BY info.REST_ID
ORDER BY SCORE DESC, info.FAVORITES DESC;