-- 코드를 입력하세요
/** 
1. SELECT : 자동차 ID, AVAILABILITY
2. 2022.10.16일에 대여 중(START_DATE <= 2022.10.16 && END_DATE >= 2022.10.16)인
    자동차는 AVAILABILITY = '대여중' <-> '대여 가능'
3. 자동차 ID 기준 내림차순
**/

SELECT CAR_ID,
    MAX(CASE
        WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN '대여중' 
        ELSE '대여 가능'
    END) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;